plugins:
  - jest
  - fp

env:
  es2021: true
  node: true

extends:
  - airbnb-base
  - plugin:jest/recommended
  - plugin:fp/recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extensions:
   - error
   - ignorePackages
   - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  fp/no-unused-expression: 0
  fp/no-nil: 0
  fp/no-throw: 0
